In [21]:
import pandas as pd
import numpy as np
import os
import re

In [22]:
# root_dir_person = "data_person"
# root_dir_metric = "data_metric"

# filenames = os.listdir(root_dir_person)

# # Function to extract the participant identifier from the filename
# def extract_participant_id(filename):
#     match = re.match(r"(\d+-[AP]MPerson\d+D\d)", filename)
#     if match:
#         return match.group(1)
#     return None

# # Get a list of unique participants
# unique_participants = list(set(filter(None, [extract_participant_id(f) for f in filenames])))

# print("Unique participants:", unique_participants)

Unique participants: ['2-PMPerson2D1', '3-AMPerson3D3', '2-PMPerson2D2', '2-PMPerson2D3', '5-PMPerson5D2', '6-AMPerson6D2', '2-AMPerson2D2', '8-PMPerson8D2', '7-PMPerson7D1', '9-PMPerson9D1', '7-AMPerson7D3', '4-PMPerson4D2', '4-AMPerson4D1', '6-PMPerson6D2', '8-AMPerson8D1', '2-AMPerson2D3', '6-PMPerson6D3', '8-PMPerson8D3', '9-AMPerson9D1', '9-PMPerson9D3', '4-AMPerson4D3', '9-PMPerson9D2', '4-AMPerson4D2', '4-PMPerson4D3', '7-AMPerson7D2', '7-AMPerson7D1', '1-AMPerson1D1', '3-AMPerson3D2', '10-PMPerson10D2', '8-AMPerson8D3', '2-AMPerson2D1', '5-AMPerson5D1', '4-PMPerson4D1', '3-PMPerson3D2', '5-PMPerson5D1', '8-PMPerson8D1', '3-PMPerson3D3', '3-AMPerson3D1', '5-PMPerson5D3', '6-PMPerson6D1', '1-PMPerson1D2', '9-AMPerson9D3', '1-AMPerson1D3', '5-AMPerson5D3', '7-PMPerson7D3', '10-PMPerson10D3', '1-AMPerson1D2', '10-AMPerson10D2', '1-PMPerson1D1', '5-AMPerson5D2', '6-AMPerson6D1', '10-AMPerson10D1', '8-AMPerson8D2', '10-AMPerson10D3', '1-PMPerson1D3', '7-PMPerson7D2', '10-PMPerson10D1', '3-PMPerson3D1', '6-AMPerson6D3', '9-AMPerson9D2']

In [ ]:
data_metric = pd.read_csv(f"{root_dir_metric}/Data Set EEG ONLY v2 (Day 1 - Attention) - Sheet1.csv")

In [23]:
data_metric = pd.read_csv(f"{root_dir_metric}/Data Set EEG ONLY v2 (Day 1 - Attention) - Sheet1.csv")

# Transpose the DataFrame
transposed_data_metric = data_metric.transpose()

# Set the second row (index 1) as the header
new_header = transposed_data_metric.iloc[1]  # second row as header
transposed_data_metric = transposed_data_metric[2:]  # data starts from the third row
transposed_data_metric.columns = new_header  # set the header

# Optionally, reset the index to get the columns back to default integer indices
transposed_data_metric.reset_index(drop=True, inplace=True)

transposed_data_metric

Unnamed: 1,NaN,NaN,Participant ID,1-AMPerson1D1,1-PMPerson1D1,10-AMPerson10D1,10-PMPerson10D1,2-AMPerson2D1,2-PMPerson2D1,3-AMPerson3D1,...,5-AMPerson5D1,5-PMPerson5D1,6-AMPerson6D1,6-PMPerson6D1,7-AMPerson7D1,7-PMPerson7D1,8-AMPerson8D1,8-PMPerson8D1,9-AMPerson9D1,9-PMPerson9D1
0,NaN,NaN,Participant Name,John Carlo,Fernando,Jaden,Jay,Kristine,Bill,Fhilip,...,Timothy,Nathalie,Josef,Peter Alfonso,Henmar,Xeann Matthew,Felipe,John Caleb,Camille,Mark James
1,NaN,NaN,Day Number,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,NaN,NaN,Session,Morning,Afternoon,Morning,Afternoon,Morning,Afternoon,Morning,...,Morning,Afternoon,Morning,Afternoon,Morning,Afternoon,Morning,Afternoon,Morning,Afternoon
3,June,NE Online,Test 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Test 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7351,Live,Max,15:39:05.033719,NaN,-4.910878,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7352,Live,Min,15:39:19.053473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.017278
7353,Live,Max,15:39:19.053473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.698471
7354,Live,Min,15:39:39.262892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.006492
7355,Live,Max,15:39:39.262892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.725404